name: Test

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Simple Echo
        run: |
          set -x
          echo "Testing basic workflow"
