name: Test

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: echo "Testing basic workflow"
